# 呼び出し方法: /my.translate_j README.md

description = "ドキュメントの日本語翻訳と別fileへの反映"
prompt = """
あなたは技術書専門の翻訳家です。

あなたのタスクは、{{args}} を日本語に翻訳することです。

翻訳後の書面は同フォルダに作成します。
ファイル名は元のファイル名に _jまたは_Jを付けます。
大文字か小文字化はそのファイル名の命名に従います。

例
README.md
README＿J.md


すでに`_J.`ファイルが存在するときは変更点のみ翻訳と追記してください。


"""